### ISSUE TITLE
device.template.area 中y坐标计算的问题

### ISSUE THREAD

**Issue by kurisu0725** [Aues6uen11Z/Zafkiel#1]
我在使用作者的HonkaiHelper的代码时，其中Template填写的x,y坐标应该指的是 相对于窗口中心点的坐标吧？scale为(-0.5,0.5)。
设置的相对位置如下：
![image](https://github.com/user-attachments/assets/4a6f0683-03aa-49b3-aeba-efa61aadc713)

在调试过程中发现area计算的y出现负值，如下：
![image](https://github.com/user-attachments/assets/f72ef7c1-2935-4331-998b-e80886cc3519)

![28a46e18adf9c92d73aca800c59438f1](https://github.com/user-attachments/assets/db09fcfc-56fd-4ebe-a634-ad47b23868cc)
随后发现area函数中，y的计算和x一样都写成了screen_width。
![image](https://github.com/user-attachments/assets/7c1f11f4-3adc-469b-83c2-a87b2e8657c6)

修改后，输出的坐标正常。
![28a46e18adf9c92d73aca800c59438f1](https://github.com/user-attachments/assets/35d16785-76f7-4868-8065-d677d44a2db8)
![image](https://github.com/user-attachments/assets/5d2a5681-6a43-4943-bfc9-1998c2592b0a)

**Comment by Aues6uen11Z** [comment]
非常高兴你有兴趣读这个没写文档的项目，但这个Template所填写的坐标是由AirtestIDE生成的，MAIN_FLAG正常位置是(0.281, 0.043)，比例都是根据宽度计算的，可以看[这里](https://github.com/AirtestProject/Airtest/blob/667896944d7c76f349a75c01133d532a99de4762/airtest/core/cv.py#L272)。

能算出负值其实正是这一点的体现，因为都是按宽度计算，16:9画面y轴取值是(-0.28125, 0.28125)，即9/16/2。

**Comment by kurisu0725** [comment]
> 非常高兴你有兴趣读这个没写文档的项目，但这个Template所填写的坐标是由AirtestIDE生成的，MAIN_FLAG正常位置是(0.281, 0.043)，比例都是根据宽度计算的，可以看[这里](https://github.com/AirtestProject/Airtest/blob/667896944d7c76f349a75c01133d532a99de4762/airtest/core/cv.py#L272)。
> 
> 能算出负值其实正是这一点的体现，因为都是按宽度计算，16:9画面y轴取值是(-0.28125, 0.28125)，即9/16/2。

我懂了，按宽度算，只要给定的(x,y)也是按这个方式计算的，最终得到的坐标其实是一样的。我看到坐标是小于1的正负时第一时间认为都是按各自的长度计算的，然后库函数里按宽度算，所以会出现错误。那为什么airtest是按宽度算的呢？这是通用的写法么，还是偏好？
我没有开发经验，无意中看到了SRC的那个项目，结构有点复杂，然后读了HonkaiHelper，就打算试试。

**Comment by Aues6uen11Z** [comment]
> 那为什么airtest是按宽度算的呢？这是通用的写法么，还是偏好？

这个不太清楚，我也没看过其他的类似库

我刚发现原来你那个MAIN_FLAG是自己项目里的，最近我会补上文档说下这个库怎么用，之前觉得没人用一直懒得写_ (:з」∠)_

**Comment by kurisu0725** [comment]
> > 那为什么airtest是按宽度算的呢？这是通用的写法么，还是偏好？
> 
> 这个不太清楚，我也没看过其他的类似库
> 
> 我刚发现原来你那个MAIN_FLAG是自己项目里的，最近我会补上文档说下这个库怎么用，之前觉得没人用一直懒得写_ (:з」∠)_

感谢，我先照着项目写写看
